export const UPDATE_SEARCH_INPUT = "UPDATE_SEARCH_INPUT";
export const SET_SUBMITTED_TERM = "SET_SUBMITTED_TERM";
export const SET_WEIRDNESS_LEVEL = "SET_WEIRDNESS_LEVEL";
export const SET_RESULT = "SET_RESULT";
export const ADD_FAVORITE = "ADD_FAVORITE";
export const CLEAR_RESULTS = "CLEAR_RESULTS";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";
